version: '3.8'

volumes:
  mongo_vol:

services:
  mongodb:
    image: mongo:4.4.3
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo_vol:/data/db

  mongo-express:
    image: mongo-express:1-20
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
