version: '3.8'

volumes:
  mongo_vol:

services:
  mongodb:
    image: mongo:${MONGO_VERSION}
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_vol:/data/db

  mongo-express:
    image: mongo-express:${MONGOEXPRESS_VERSION}
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "${MONGOEXPRESS_PORT}:8081"
