version: '3.8'

volumes:
  db_vol:
  wordpress_vol:

services:
  db:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - db_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DATABASE}
      MYSQL_USER: ${WORDPRESS_USERNAME}
      MYSQL_PASSWORD: ${WORDPRESS_PASSWORD}
    restart: always

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_USERNAME}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DATABASE}
    restart: always
    volumes:
      - wordpress_vol:/var/www/html
